"""
Personal AI OS - Rule Cluster Model

Groups semantically similar rules into clusters for deduplication
and organization insights.
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Table
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.session import Base


# Many-to-many join table: clusters ↔ rules
rule_cluster_members = Table(
    "rule_cluster_members",
    Base.metadata,
    Column("cluster_id", UUID(as_uuid=True), ForeignKey("rule_clusters.id", ondelete="CASCADE"), primary_key=True),
    Column("rule_id", UUID(as_uuid=True), ForeignKey("rules.id", ondelete="CASCADE"), primary_key=True),
    Column("similarity_to_centroid", Float, default=0.0),
    Column("added_at", DateTime, default=datetime.utcnow),
)


class RuleCluster(Base):
    """
    A cluster of semantically similar rules.

    Generated by running pairwise FAISS similarity over a user's
    active rules and grouping those above a configurable threshold.
    """

    __tablename__ = "rule_clusters"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    name = Column(String(255), nullable=False)
    description = Column(String(1000))
    rule_count = Column(Integer, default=0)

    # Average intra-cluster similarity
    avg_similarity = Column(Float, default=0.0)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = relationship("User")
    rules = relationship("Rule", secondary=rule_cluster_members, backref="clusters")

    def __repr__(self):
        return f"<RuleCluster {self.id}: {self.name} ({self.rule_count} rules)>"

    def to_dict(self):
        return {
            "id": str(self.id),
            "user_id": str(self.user_id),
            "name": self.name,
            "description": self.description,
            "rule_count": self.rule_count,
            "avg_similarity": round(self.avg_similarity, 3) if self.avg_similarity else 0,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
